language: node_js
node_js:
- 'node'
script:
- bash ./deploy.sh
branches:
  only: master
env:
  global:
    secure: "kkt1NmRRmw4oguuq60kLUX/iK/Dxz04PnLGVyYCdzp9dk402/uQCs/AbDdKcjON15A7KM1sr8q/39eHbYgOoYZNSuPG3JObYcVEKEZtEvSmSKxPj0mjayu7C6rYg55nckMa26J4UYkewXc1DAz55U/WKOaG0N/zen+NXK1QbBoY="

